#!/usr/bin/env python3
from __future__ import print_function, division
import h5py
import numpy as np

def iqr(x):
    return np.percentile(x,75) - np.percentile(x,25)

def get_times(x, data, baseline=10):
    """
    Returns the times at which the waveforms in `x` cross 40% of their minimum
    value.
    """
    data = np.asarray(data)
    # Get the first 10 ns of every waveform to calculate the noise level
    noise = iqr(data[:,np.where(x < x[0] + baseline)[0]])
    # Get events with a pulse
    pulses = np.min(data,axis=-1) < -noise*5
    # Select events with pulses. If there are no matches (which might be the
    # case for the triggering channel), then don't apply the selection.
    if np.count_nonzero(pulses):
        data = data[pulses]
    argmin = np.argmin(data,axis=-1)
    threshold = 0.4*data[np.arange(data.shape[0]),argmin]
    return x[data.shape[1]-np.argmax(((np.arange(data.shape[1]) < argmin[:,np.newaxis]) & (data > threshold[:,np.newaxis]))[:,::-1],axis=-1)-1]

def get_window(x, data, left=1, right=10):
    """
    Returns the indices start and stop over which you should integrate the
    waveforms in `x`. The window is found by calculating the median hit time
    for all pulses in `x` and then going back 10 ns and forward 125 ns for sodium and 10 ns otherwise.
    """
    data = np.asarray(data)
    t = get_times(x,data)
    mean_hit_time = np.median(t)
    a, b = np.searchsorted(x,[mean_hit_time-left,mean_hit_time+right])
    if a < 0:
        a = 0
    if b > len(x) - 1:
        b = len(x) - 1
    return a, b

def integrate(x, data, a, b):
    """
    Integrate all waveforms in `data` with times `x`.
    """
    
    # i = v/r
    # divide by 50 ohms to convert to a charge
    return -np.trapz(data[:,a:b],x=x[a:b])*1000/50.0

def get_bins(x):
    """
    Returns bins for the data `x` using the Freedman Diaconis rule. See
    https://en.wikipedia.org/wiki/Freedman%E2%80%93Diaconis_rule.
    
    The equation below returns bins using said rule. A smaller bin value than this was chosen after finetuning for better fitting results.
    bin_width = 2*iqr(x)/(len(x)**(1/3.0))
    """
    
    bin_width = 0.5*iqr(x)/(len(x)**(1/3.0))
    return np.arange(np.min(x),np.max(x),bin_width)

if __name__ == '__main__':
    from argparse import ArgumentParser
    import ROOT
    import matplotlib.pyplot as plt
    import psycopg2
    import psycopg2.extensions
    import os
    import sys

    parser = ArgumentParser(description='Analyze data from the Agilent scope')
    parser.add_argument('filenames',nargs='+',help='input filenames (hdf5 format)')
    parser.add_argument('-o','--output', default=None, help='output file name', required=True)
    parser.add_argument('--plot', default=False, action='store_true', help='plot the waveforms and charge integral')
    args = parser.parse_args()

    charge = {}
    for filename in args.filenames:
        with h5py.File(filename) as f:
            x = np.linspace(0,f.attrs['record_length']*1e3/f.attrs['drs4_frequency'],f.attrs['record_length'])
            for i in range(16):
                channel = 'ch%i' % i

                if channel not in f:
                    print("failed to find channel %i" % i)
                    continue

                y = f[channel][:]*2/0xfff

                # Remove baseline
                y -= np.median(y[:,:100],axis=-1)[:,np.newaxis]

                a, b = get_window(x,y,left=20,right=400)
                
                charge[channel] = integrate(x,y, a, b)
                
                if args.plot:
                    plt.subplot(4,4,i+1)
                    plt.plot(x,y[:100].T)
                    plt.xlabel("Time (ns)")
                    plt.ylabel("Voltage (V)")
                    plt.title(channel)
                    plt.axvline(x[a])
                    plt.axvline(x[b])

    if args.plot:
        plt.figure()

    data = {}

    f = ROOT.TFile(args.output,"recreate")
    for i in range(16):
        channel = 'ch%i' % i

        if channel not in charge:
            continue

        bins = get_bins(charge[channel])
        hist, bins = np.histogram(charge[channel],bins=bins)
        bincenters = (bins[1:] + bins[:-1])/2
        h = ROOT.TH1D(channel,"Charge Integral for %s" % channel,len(bins),bins[0],bins[-1])
        for x in charge[channel]:
            h.Fill(x)
        h.GetXaxis().SetTitle("Charge (pC)")

        data['ch%i_511' % i] = bincenters[np.argmax(hist)]
        
        if args.plot:
            plt.subplot(4,4,i+1)
            plt.hist(charge[channel],bins=bins,histtype='step')
            plt.xlabel("Charge (pC)")
            plt.title(channel)

        h.Write()

    f.Close()

    for i in range(16,32):
        data['ch%i_511' % i] = None

    if 'BTL_DB_PASSWORD' not in os.environ:
        print("need to set BTL_DB_PASSWORD environment variable!",file=sys.stderr)
        sys.exit(1)

    conn = psycopg2.connect(dbname='btl_qa',
                            user='btl_test',
                            host='localhost',
                            password=os.environ['BTL_DB_PASSWORD'])
    conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)

    cursor = conn.cursor()
    cursor.execute("INSERT INTO btl_qa ("
        "ch0_511  , "
        "ch1_511  , "
        "ch2_511  , "
        "ch3_511  , "
        "ch4_511  , "
        "ch5_511  , "
        "ch6_511  , "
        "ch7_511  , "
        "ch8_511  , "
        "ch9_511  , "
        "ch10_511 , "
        "ch11_511 , "
        "ch12_511 , "
        "ch13_511 , "
        "ch14_511 , "
        "ch15_511 , "
        "ch16_511 , "
        "ch17_511 , "
        "ch18_511 , "
        "ch19_511 , "
        "ch20_511 , "
        "ch21_511 , "
        "ch22_511 , "
        "ch23_511 , "
        "ch24_511 , "
        "ch25_511 , "
        "ch26_511 , "
        "ch27_511 , "
        "ch28_511 , "
        "ch29_511 , "
        "ch30_511 , "
        "ch31_511 , "
        "institution) VALUES ("
        "%(ch0_511)s, "
        "%(ch1_511)s, "
        "%(ch2_511)s, "
        "%(ch3_511)s, "
        "%(ch4_511)s, "
        "%(ch5_511)s, "
        "%(ch6_511)s, "
        "%(ch7_511)s, "
        "%(ch8_511)s, "
        "%(ch9_511)s, "
        "%(ch10_511)s, "
        "%(ch11_511)s, "
        "%(ch12_511)s, "
        "%(ch13_511)s, "
        "%(ch14_511)s, "
        "%(ch15_511)s, "
        "%(ch16_511)s, "
        "%(ch17_511)s, "
        "%(ch18_511)s, "
        "%(ch19_511)s, "
        "%(ch20_511)s, "
        "%(ch21_511)s, "
        "%(ch22_511)s, "
        "%(ch23_511)s, "
        "%(ch24_511)s, "
        "%(ch25_511)s, "
        "%(ch26_511)s, "
        "%(ch27_511)s, "
        "%(ch28_511)s, "
        "%(ch29_511)s, "
        "%(ch30_511)s, "
        "%(ch31_511)s, "
        "'Caltech'::inst)",
        data)

    if args.plot:
        plt.show()
